/* =========================================================
   RETAIL SALES ANALYSIS PROJECT
   =========================================================

   File Name : Business_Analysis.sql

   Purpose
   -------
   This file contains business-oriented SQL queries used
   to analyze sales, profit, customers, products, regions,
   discounts, shipping performance and business trends.

   Database
   --------
   retail_sales_analysis

   Tables
   ------
   customers
   products
   orders
   sales

   Analysis Areas
   --------------
   01. Overall Business Performance
   02. Sales Analysis
   03. Profit Analysis
   04. Product Analysis
   05. Customer Analysis
   06. Category & Sub-category Analysis
   07. Regional Analysis
   08. Time Analysis
   09. Discount Analysis
   10. Shipping Analysis
   11. Customer Segmentation
   12. Advanced Business Analysis

   ========================================================= */

USE retail_sales_analysis;

/* =========================================================
   SECTION 01
   OVERALL BUSINESS PERFORMANCE
   ========================================================= */

/* ---------------------------------------------------------
   Q01. What is the total sales generated by the business?
   --------------------------------------------------------- */
SELECT
    ROUND(SUM(Sales), 2) AS Total_Sales
FROM sales;

/* ---------------------------------------------------------
   Q02. What is the total profit generated by the business?
   --------------------------------------------------------- */
SELECT
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales;

/* ---------------------------------------------------------
   Q03. What is the total quantity sold?
   --------------------------------------------------------- */
SELECT
    SUM(Quantity) AS Total_Quantity
FROM sales;

/* ---------------------------------------------------------
   Q04. How many unique orders were placed?
   --------------------------------------------------------- */
SELECT
    COUNT(DISTINCT Order_ID) AS Total_Orders
FROM sales;

/* ---------------------------------------------------------
   Q05. How many unique customers purchased products?
   --------------------------------------------------------- */
SELECT
    COUNT(DISTINCT o.Customer_ID) AS Total_Customers
FROM orders o
INNER JOIN sales s
    ON o.Order_ID = s.Order_ID;

/* ---------------------------------------------------------
   Q06. What is the overall profit margin?
   --------------------------------------------------------- */
SELECT
    ROUND(
        SUM(Profit) / NULLIF(SUM(Sales), 0) * 100,
        2
    ) AS Profit_Margin_Percentage

FROM sales;

/* ---------------------------------------------------------
   Q07. What is the average order value?
   --------------------------------------------------------- */

SELECT

    ROUND(
        SUM(Sales) / COUNT(DISTINCT Order_ID),
        2
    ) AS Average_Order_Value

FROM sales;

/* ---------------------------------------------------------
   Q08. What is the average discount given?
   --------------------------------------------------------- */
SELECT
    ROUND(AVG(Discount) * 100, 2) AS Average_Discount_Percentage
FROM sales;

/* =========================================================
   SECTION 02
   SALES ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q09. Which category generates the highest sales?
   --------------------------------------------------------- */
SELECT
    p.Category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Sales DESC;
/* ---------------------------------------------------------
   Q10. Which sub-category generates the highest sales?
   --------------------------------------------------------- */
SELECT
    p.Sub_category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Sub_category
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q11. What are the top 10 products by sales?
   --------------------------------------------------------- */
SELECT
    p.Product_ID,
    p.Product_name,
    p.Category,
    p.Sub_category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_name,
    p.Category,
    p.Sub_category
ORDER BY Total_Sales DESC
LIMIT 10;

/* ---------------------------------------------------------
   Q12. What are the bottom 10 products by sales?
   --------------------------------------------------------- */
SELECT
    p.Product_ID,
    p.Product_name,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_name
ORDER BY Total_Sales ASC
LIMIT 10;

/* ---------------------------------------------------------
   Q13. Which region generates the highest sales?
   --------------------------------------------------------- */
SELECT
    o.Region,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY o.Region
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q14. Which state generates the highest sales?
   --------------------------------------------------------- */
SELECT
    o.State,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY o.State
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q15. Which city generates the highest sales?
   --------------------------------------------------------- */
SELECT
    o.City,
    o.State,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY
    o.City,
    o.State
ORDER BY Total_Sales DESC
LIMIT 20;

/* =========================================================
   SECTION 03
   PROFIT ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q16. Which category generates the highest profit?
   --------------------------------------------------------- */
SELECT
    p.Category,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Profit DESC;

/* ---------------------------------------------------------
   Q17. Which sub-category generates the highest profit?
   --------------------------------------------------------- */
SELECT
    p.Sub_category,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Sub_category
ORDER BY Total_Profit DESC;

/* ---------------------------------------------------------
   Q18. Which sub-categories are loss-making?
   --------------------------------------------------------- */
SELECT
    p.Sub_category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Sub_category
HAVING SUM(s.Profit) < 0
ORDER BY Total_Profit ASC;

/* ---------------------------------------------------------
   Q19. Which products generate an overall loss?
   --------------------------------------------------------- */
SELECT
    p.Product_ID,
    p.Product_name,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_name
HAVING SUM(s.Profit) < 0
ORDER BY Total_Profit ASC;

/* ---------------------------------------------------------
   Q20. Which are the top 10 most profitable products?
   --------------------------------------------------------- */
SELECT
    p.Product_ID,
    p.Product_name,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_name
ORDER BY Total_Profit DESC
LIMIT 10;

/* ---------------------------------------------------------
   Q21. Which regions generate the highest profit?
   --------------------------------------------------------- */
SELECT
    o.Region,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin_Percentage
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY o.Region
ORDER BY Total_Profit DESC;

/* =========================================================
   SECTION 04
   CATEGORY & SUB-CATEGORY ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q22. Compare sales, quantity and profit by category.
   --------------------------------------------------------- */
SELECT
    p.Category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    SUM(s.Quantity) AS Total_Quantity,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin_Percentage
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q23. Compare all sub-categories by sales and profit.
   --------------------------------------------------------- */
SELECT
    p.Category,
    p.Sub_category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    SUM(s.Quantity) AS Total_Quantity
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Category,
    p.Sub_category
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q24. Which sub-categories have high sales but low profit?
   --------------------------------------------------------- */
SELECT
    p.Sub_category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Sub_category
HAVING SUM(s.Sales) > 10000
ORDER BY Profit_Margin ASC;

/* =========================================================
   SECTION 05
   CUSTOMER ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q25. Which customers generate the highest sales?
   --------------------------------------------------------- */
SELECT
    c.Customer_ID,
    c.Customer_Name,
    c.Segment,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
INNER JOIN customers c
    ON o.Customer_ID = c.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name,
    c.Segment
ORDER BY Total_Sales DESC
LIMIT 10;

/* ---------------------------------------------------------
   Q26. Which customers generate the highest profit?
   --------------------------------------------------------- */
SELECT
    c.Customer_ID,
    c.Customer_Name,
    c.Segment,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
INNER JOIN customers c
    ON o.Customer_ID = c.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name,
    c.Segment
ORDER BY Total_Profit DESC
LIMIT 10;

/* ---------------------------------------------------------
   Q27. Which customer segment generates the most sales?
   --------------------------------------------------------- */
SELECT
    c.Segment,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    COUNT(DISTINCT c.Customer_ID) AS Customers
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
INNER JOIN customers c
    ON o.Customer_ID = c.Customer_ID
GROUP BY c.Segment
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q28. Which customer segment is the most profitable?
   --------------------------------------------------------- */
SELECT
    c.Segment,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
INNER JOIN customers c
    ON o.Customer_ID = c.Customer_ID
GROUP BY c.Segment
ORDER BY Total_Profit DESC;

/* ---------------------------------------------------------
   Q29. What is the average sales value per customer?
   --------------------------------------------------------- */
SELECT
    ROUND(
        SUM(s.Sales) /
        COUNT(DISTINCT o.Customer_ID),
        2
    ) AS Sales_Per_Customer
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID;

/* ---------------------------------------------------------
   Q30. Which customers have placed the most orders?
   --------------------------------------------------------- */
SELECT
    c.Customer_ID,
    c.Customer_Name,
    COUNT(DISTINCT o.Order_ID) AS Total_Orders
FROM customers c
INNER JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name
ORDER BY Total_Orders DESC
LIMIT 10;

/* =========================================================
   SECTION 06
   TIME-BASED ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q31. What are the yearly sales and profit trends?
   --------------------------------------------------------- */
SELECT
    YEAR(o.Order_Date) AS Sales_Year,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY YEAR(o.Order_Date)
ORDER BY Sales_Year;

/* ---------------------------------------------------------
   Q32. What are the monthly sales trends?
   --------------------------------------------------------- */
SELECT
    YEAR(o.Order_Date) AS Sales_Year,
    MONTH(o.Order_Date) AS Sales_Month,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY
    YEAR(o.Order_Date),
    MONTH(o.Order_Date)
ORDER BY
    Sales_Year,
    Sales_Month;

/* ---------------------------------------------------------
   Q33. What are the monthly profit trends?
   --------------------------------------------------------- */
SELECT
    YEAR(o.Order_Date) AS Sales_Year,
    MONTH(o.Order_Date) AS Sales_Month,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY
    YEAR(o.Order_Date),
    MONTH(o.Order_Date)
ORDER BY
    Sales_Year,
    Sales_Month;

/* ---------------------------------------------------------
   Q34. Which month generated the highest sales?
   --------------------------------------------------------- */
SELECT
    YEAR(o.Order_Date) AS Sales_Year,
    MONTH(o.Order_Date) AS Sales_Month,
    ROUND(SUM(s.Sales), 2) AS Total_Sales
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY
    YEAR(o.Order_Date),
    MONTH(o.Order_Date)
ORDER BY Total_Sales DESC
LIMIT 1;

/* ---------------------------------------------------------
   Q35. Which month generated the highest profit?
   --------------------------------------------------------- */
SELECT
    YEAR(o.Order_Date) AS Sales_Year,
    MONTH(o.Order_Date) AS Sales_Month,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY
    YEAR(o.Order_Date),
    MONTH(o.Order_Date)
ORDER BY Total_Profit DESC
LIMIT 1;

/* =========================================================
   SECTION 07
   DISCOUNT ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q36. What is the relationship between discount level
        and profit?
   --------------------------------------------------------- */
SELECT
    Discount,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(AVG(Profit), 2) AS Average_Profit
FROM sales
GROUP BY Discount
ORDER BY Discount;

/* ---------------------------------------------------------
   Q37. Which discount levels generate negative profit?
   --------------------------------------------------------- */
SELECT
    Discount,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM sales
GROUP BY Discount
HAVING SUM(Profit) < 0
ORDER BY Discount;

/* ---------------------------------------------------------
   Q38. Compare sales and profit across discount ranges.
   --------------------------------------------------------- */
SELECT
    CASE
        WHEN Discount = 0
            THEN 'No Discount'
        WHEN Discount <= 0.20
            THEN 'Low Discount'
        WHEN Discount <= 0.50
            THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS Discount_Band,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(
        SUM(Profit) /
        NULLIF(SUM(Sales), 0) * 100,
        2
    ) AS Profit_Margin
FROM sales
GROUP BY
    CASE
        WHEN Discount = 0
            THEN 'No Discount'
        WHEN Discount <= 0.20
            THEN 'Low Discount'
        WHEN Discount <= 0.50
            THEN 'Medium Discount'
        ELSE 'High Discount'
    END
ORDER BY Total_Sales DESC;

/* =========================================================
   SECTION 08
   SHIPPING ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q39. Which shipping mode is most commonly used?
   --------------------------------------------------------- */
SELECT
    o.Ship_Mode,
    COUNT(DISTINCT o.Order_ID) AS Total_Orders
FROM orders o
GROUP BY o.Ship_Mode
ORDER BY Total_Orders DESC;

/* ---------------------------------------------------------
   Q40. Which shipping mode generates the highest sales?
   --------------------------------------------------------- */
SELECT
    o.Ship_Mode,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY o.Ship_Mode
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q41. What is the average shipping time by ship mode?
   --------------------------------------------------------- */
SELECT
    Ship_Mode,
    ROUND(
        AVG(DATEDIFF(Ship_Date, Order_Date)),
        2
    ) AS Average_Shipping_Days
FROM orders
GROUP BY Ship_Mode
ORDER BY Average_Shipping_Days;

/* ---------------------------------------------------------
   Q42. Which orders took more than 5 days to ship?
   --------------------------------------------------------- */
SELECT
    Order_ID,
    Customer_ID,
    Order_Date,
    Ship_Date,
    Ship_Mode,
    DATEDIFF(Ship_Date, Order_Date) AS Shipping_Days
FROM orders
WHERE DATEDIFF(Ship_Date, Order_Date) > 5
ORDER BY Shipping_Days DESC;

/* =========================================================
   SECTION 09
   REGIONAL ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q43. Compare sales and profit across regions.
   --------------------------------------------------------- */
SELECT
    o.Region,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    SUM(s.Quantity) AS Total_Quantity,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY o.Region
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q44. Which states generate sales but negative profit?
   --------------------------------------------------------- */
SELECT
    o.State,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY o.State
HAVING SUM(s.Profit) < 0
ORDER BY Total_Profit ASC;

/* ---------------------------------------------------------
   Q45. Which cities have the highest profit?
   --------------------------------------------------------- */
SELECT
    o.City,
    o.State,
    ROUND(SUM(s.Profit), 2) AS Total_Profit
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
GROUP BY
    o.City,
    o.State
ORDER BY Total_Profit DESC
LIMIT 20;

/* =========================================================
   SECTION 10
   ADVANCED BUSINESS ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q46. Rank products by total sales.
   --------------------------------------------------------- */
WITH ProductSales AS (
    SELECT
        p.Product_ID,
        p.Product_name,
        ROUND(SUM(s.Sales), 2) AS Total_Sales
    FROM sales s
    INNER JOIN products p
        ON s.Product_ID = p.Product_ID
    GROUP BY
        p.Product_ID,
        p.Product_name
)
SELECT
    Product_ID,
    Product_name,
    Total_Sales,
    RANK() OVER (
        ORDER BY Total_Sales DESC
    ) AS Sales_Rank
FROM ProductSales
ORDER BY Sales_Rank;

/* ---------------------------------------------------------
   Q47. Rank categories by profit.
   --------------------------------------------------------- */
WITH CategoryProfit AS (
    SELECT
        p.Category,
        ROUND(SUM(s.Profit), 2) AS Total_Profit
    FROM sales s
    INNER JOIN products p
        ON s.Product_ID = p.Product_ID
    GROUP BY p.Category
)
SELECT
    Category,
    Total_Profit,
    RANK() OVER (
        ORDER BY Total_Profit DESC
    ) AS Profit_Rank
FROM CategoryProfit
ORDER BY Profit_Rank;

/* ---------------------------------------------------------
   Q48. Find the top 3 products within each category
        based on sales.
   --------------------------------------------------------- */
WITH ProductSales AS (
    SELECT
        p.Category,
        p.Product_ID,
        p.Product_name,
        SUM(s.Sales) AS Total_Sales
    FROM sales s
    INNER JOIN products p
        ON s.Product_ID = p.Product_ID
    GROUP BY
        p.Category,
        p.Product_ID,
        p.Product_name
),
RankedProducts AS (
    SELECT
        Category,
        Product_ID,
        Product_name,
        ROUND(Total_Sales, 2) AS Total_Sales,
        ROW_NUMBER() OVER (
            PARTITION BY Category
            ORDER BY Total_Sales DESC
        ) AS Product_Rank
    FROM ProductSales
)
SELECT *
FROM RankedProducts
WHERE Product_Rank <= 3
ORDER BY
    Category,
    Product_Rank;

/* ---------------------------------------------------------
   Q49. Calculate each category's contribution to total sales.
   --------------------------------------------------------- */
WITH CategorySales AS (
    SELECT
        p.Category,
        SUM(s.Sales) AS Total_Sales
    FROM sales s
    INNER JOIN products p
        ON s.Product_ID = p.Product_ID
    GROUP BY p.Category
)
SELECT
    Category,
    ROUND(Total_Sales, 2) AS Total_Sales,
    ROUND(
        Total_Sales /
        SUM(Total_Sales) OVER () * 100,
        2
    ) AS Sales_Contribution_Percentage
FROM CategorySales
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q50. Calculate each region's contribution to total sales.
   --------------------------------------------------------- */
WITH RegionSales AS (
    SELECT
        o.Region,
        SUM(s.Sales) AS Total_Sales
    FROM sales s
    INNER JOIN orders o
        ON s.Order_ID = o.Order_ID
    GROUP BY o.Region
)
SELECT
    Region,
    ROUND(Total_Sales, 2) AS Total_Sales,
    ROUND(
        Total_Sales /
        SUM(Total_Sales) OVER () * 100,
        2
    ) AS Sales_Contribution_Percentage
FROM RegionSales
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q51. Identify customers with high sales but low profit.
   --------------------------------------------------------- */
SELECT
    c.Customer_ID,
    c.Customer_Name,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID
INNER JOIN customers c
    ON o.Customer_ID = c.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name
HAVING
    SUM(s.Sales) > 1000
    AND
    SUM(s.Profit) < 100
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q52. Identify products with high sales but low profit.
   --------------------------------------------------------- */
SELECT
    p.Product_ID,
    p.Product_name,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_name
HAVING
    SUM(s.Sales) > 1000
    AND
    SUM(s.Profit) < 100
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q53. Find the highest-value order.
   --------------------------------------------------------- */
SELECT
    s.Order_ID,
    ROUND(SUM(s.Sales), 2) AS Order_Value
FROM sales s
GROUP BY s.Order_ID
ORDER BY Order_Value DESC
LIMIT 10;

/* ---------------------------------------------------------
   Q54. Find orders with negative overall profit.
   --------------------------------------------------------- */
SELECT
    s.Order_ID,
    ROUND(SUM(s.Sales), 2) AS Order_Value,
    ROUND(SUM(s.Profit), 2) AS Order_Profit
FROM sales s
GROUP BY s.Order_ID
HAVING SUM(s.Profit) < 0
ORDER BY Order_Profit ASC;

/* ---------------------------------------------------------
   Q55. Find customers with the highest average order value.
   --------------------------------------------------------- */
WITH CustomerOrders AS (
    SELECT
        o.Customer_ID,
        s.Order_ID,
        SUM(s.Sales) AS Order_Value
    FROM sales s
    INNER JOIN orders o
        ON s.Order_ID = o.Order_ID
    GROUP BY
        o.Customer_ID,
        s.Order_ID
)
SELECT
    c.Customer_ID,
    c.Customer_Name,
    ROUND(AVG(co.Order_Value), 2) AS Average_Order_Value
FROM CustomerOrders co
INNER JOIN customers c
    ON co.Customer_ID = c.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name
ORDER BY Average_Order_Value DESC
LIMIT 20;

/* ---------------------------------------------------------
   Q56. Find repeat customers.
   --------------------------------------------------------- */
SELECT
    c.Customer_ID,
    c.Customer_Name,
    COUNT(DISTINCT o.Order_ID) AS Number_of_Orders
FROM customers c
INNER JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY
    c.Customer_ID,
    c.Customer_Name
HAVING COUNT(DISTINCT o.Order_ID) > 1
ORDER BY Number_of_Orders DESC;

/* ---------------------------------------------------------
   Q57. What percentage of customers are repeat customers?
   --------------------------------------------------------- */
WITH CustomerOrderCounts AS (
    SELECT
        Customer_ID,
        COUNT(DISTINCT Order_ID) AS Order_Count
    FROM orders
    GROUP BY Customer_ID
)
SELECT
    ROUND(
        SUM(
            CASE
                WHEN Order_Count > 1 THEN 1
                ELSE 0
            END
        )
        /
        COUNT(*) * 100,
        2
    ) AS Repeat_Customer_Percentage
FROM CustomerOrderCounts;

/* =========================================================
   SECTION 11
   BUSINESS OPPORTUNITY ANALYSIS
   ========================================================= */
/* ---------------------------------------------------------
   Q58. Which categories should management prioritize
        based on sales and profit?
   --------------------------------------------------------- */
SELECT
    p.Category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin,
    CASE
        WHEN SUM(s.Profit) > 0
             AND SUM(s.Sales) > 10000
            THEN 'High Priority'
        WHEN SUM(s.Profit) > 0
            THEN 'Maintain'
        ELSE 'Review'
    END AS Business_Action
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Sales DESC;

/* ---------------------------------------------------------
   Q59. Identify products requiring management review.
   --------------------------------------------------------- */
SELECT
    p.Product_ID,
    p.Product_name,
    p.Category,
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin,
    CASE
        WHEN SUM(s.Profit) < 0
            THEN 'Loss Making'
        WHEN SUM(s.Profit) /
             NULLIF(SUM(s.Sales), 0) < 0.05
            THEN 'Low Margin'
        ELSE 'Healthy'
    END AS Product_Status
FROM sales s
INNER JOIN products p
    ON s.Product_ID = p.Product_ID
GROUP BY
    p.Product_ID,
    p.Product_name,
    p.Category
ORDER BY Total_Profit ASC;

/* ---------------------------------------------------------
   Q60. Create an executive-level business summary.
   --------------------------------------------------------- */
SELECT
    ROUND(SUM(s.Sales), 2) AS Total_Sales,
    ROUND(SUM(s.Profit), 2) AS Total_Profit,
    SUM(s.Quantity) AS Total_Quantity,
    COUNT(DISTINCT s.Order_ID) AS Total_Orders,
    COUNT(DISTINCT o.Customer_ID) AS Total_Customers,
    ROUND(
        SUM(s.Profit) /
        NULLIF(SUM(s.Sales), 0) * 100,
        2
    ) AS Profit_Margin,
    ROUND(
        SUM(s.Sales) /
        COUNT(DISTINCT s.Order_ID),
        2
    ) AS Average_Order_Value
FROM sales s
INNER JOIN orders o
    ON s.Order_ID = o.Order_ID;

/* =========================================================
   END OF BUSINESS ANALYSIS
   ========================================================= */